// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Animation1: typeof import('./components/animation1.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Circle: typeof import('./components/shapes/circle.vue')['default']
    Line: typeof import('./components/shapes/line.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialCard: typeof import('./components/SocialCard.vue')['default']
  }
}

export {}
