// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Tes': typeof import("../components/content/tes.vue")['default'],
    'AppFooter': typeof import("../components/AppFooter.vue")['default'],
    'AppHeader': typeof import("../components/AppHeader.vue")['default'],
    'BalanceAnimation': typeof import("../components/BalanceAnimation.vue")['default'],
    'BioNav': typeof import("../components/BioNav.vue")['default'],
    'BuildAnimation': typeof import("../components/BuildAnimation.vue")['default'],
    'DarkModeToggle': typeof import("../components/DarkModeToggle.vue")['default'],
    'FadeTransition': typeof import("../components/FadeTransition.vue")['default'],
    'FunAnimation': typeof import("../components/FunAnimation.vue")['default'],
    'HeadLine': typeof import("../components/HeadLine.vue")['default'],
    'ImageSelector': typeof import("../components/ImageSelector.vue")['default'],
    'Logo': typeof import("../components/Logo.vue")['default'],
    'SocialCard': typeof import("../components/SocialCard.vue")['default'],
    'SocialMediaBar': typeof import("../components/SocialMediaBar.vue")['default'],
    'SupportAnimation': typeof import("../components/SupportAnimation.vue")['default'],
    'VSvg': typeof import("../components/VSvg.vue")['default'],
    'OutlineText': typeof import("../components/outline-text.vue")['default'],
    'Project': typeof import("../components/project.vue")['default'],
    'FormsTextInput': typeof import("../components/forms/TextInput.vue")['default'],
    'IconsMenuIcon': typeof import("../components/icons/MenuIcon.vue")['default'],
    'IconsSendIcon': typeof import("../components/icons/SendIcon.vue")['default'],
    'UnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.44.7_vite@2.9.14/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default'],
    'ContentDoc': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.mjs")['default'],
    'ContentList': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentList.mjs")['default'],
    'ContentNavigation': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.mjs")['default'],
    'ContentQuery': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.mjs")['default'],
    'ContentRenderer': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.mjs")['default'],
    'Markdown': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Markdown.mjs")['default'],
    'MarkdownRenderer': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/MarkdownRenderer.mjs")['default'],
    'ProseA': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue")['default'],
    'ProseBlockquote': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue")['default'],
    'ProseCode': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default'],
    'ProseCodeInline': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default'],
    'ProseEm': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue")['default'],
    'ProseH1': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue")['default'],
    'ProseH2': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue")['default'],
    'ProseH3': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue")['default'],
    'ProseH4': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue")['default'],
    'ProseH5': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue")['default'],
    'ProseH6': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue")['default'],
    'ProseHr': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue")['default'],
    'ProseImg': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue")['default'],
    'ProseLi': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue")['default'],
    'ProseOl': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue")['default'],
    'ProseP': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue")['default'],
    'ProseStrong': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue")['default'],
    'ProseTable': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue")['default'],
    'ProseTbody': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue")['default'],
    'ProseTd': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue")['default'],
    'ProseTh': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue")['default'],
    'ProseThead': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue")['default'],
    'ProseTr': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue")['default'],
    'ProseUl': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.2/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default'],
    'ColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.1.4_vite@2.9.14/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyTes': typeof import("../components/content/tes.vue")['default'],
    'LazyAppFooter': typeof import("../components/AppFooter.vue")['default'],
    'LazyAppHeader': typeof import("../components/AppHeader.vue")['default'],
    'LazyBalanceAnimation': typeof import("../components/BalanceAnimation.vue")['default'],
    'LazyBioNav': typeof import("../components/BioNav.vue")['default'],
    'LazyBuildAnimation': typeof import("../components/BuildAnimation.vue")['default'],
    'LazyDarkModeToggle': typeof import("../components/DarkModeToggle.vue")['default'],
    'LazyFadeTransition': typeof import("../components/FadeTransition.vue")['default'],
    'LazyFunAnimation': typeof import("../components/FunAnimation.vue")['default'],
    'LazyHeadLine': typeof import("../components/HeadLine.vue")['default'],
    'LazyImageSelector': typeof import("../components/ImageSelector.vue")['default'],
    'LazyLogo': typeof import("../components/Logo.vue")['default'],
    'LazySocialCard': typeof import("../components/SocialCard.vue")['default'],
    'LazySocialMediaBar': typeof import("../components/SocialMediaBar.vue")['default'],
    'LazySupportAnimation': typeof import("../components/SupportAnimation.vue")['default'],
    'LazyVSvg': typeof import("../components/VSvg.vue")['default'],
    'LazyOutlineText': typeof import("../components/outline-text.vue")['default'],
    'LazyProject': typeof import("../components/project.vue")['default'],
    'LazyFormsTextInput': typeof import("../components/forms/TextInput.vue")['default'],
    'LazyIconsMenuIcon': typeof import("../components/icons/MenuIcon.vue")['default'],
    'LazyIconsSendIcon': typeof import("../components/icons/SendIcon.vue")['default'],
    'LazyUnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.44.7_vite@2.9.14/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default'],
    'LazyContentDoc': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.mjs")['default'],
    'LazyContentList': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentList.mjs")['default'],
    'LazyContentNavigation': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.mjs")['default'],
    'LazyContentQuery': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.mjs")['default'],
    'LazyContentRenderer': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.mjs")['default'],
    'LazyMarkdown': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Markdown.mjs")['default'],
    'LazyMarkdownRenderer': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/MarkdownRenderer.mjs")['default'],
    'LazyProseA': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue")['default'],
    'LazyProseBlockquote': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue")['default'],
    'LazyProseCode': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default'],
    'LazyProseCodeInline': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default'],
    'LazyProseEm': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue")['default'],
    'LazyProseH1': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue")['default'],
    'LazyProseH2': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue")['default'],
    'LazyProseH3': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue")['default'],
    'LazyProseH4': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue")['default'],
    'LazyProseH5': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue")['default'],
    'LazyProseH6': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue")['default'],
    'LazyProseHr': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue")['default'],
    'LazyProseImg': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue")['default'],
    'LazyProseLi': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue")['default'],
    'LazyProseOl': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue")['default'],
    'LazyProseP': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue")['default'],
    'LazyProseStrong': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue")['default'],
    'LazyProseTable': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue")['default'],
    'LazyProseTbody': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue")['default'],
    'LazyProseTd': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue")['default'],
    'LazyProseTh': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue")['default'],
    'LazyProseThead': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue")['default'],
    'LazyProseTr': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue")['default'],
    'LazyProseUl': typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.2/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default'],
    'LazyColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.1.4_vite@2.9.14/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  }
}
export const Tes: typeof import("../components/content/tes.vue")['default']
export const AppFooter: typeof import("../components/AppFooter.vue")['default']
export const AppHeader: typeof import("../components/AppHeader.vue")['default']
export const BalanceAnimation: typeof import("../components/BalanceAnimation.vue")['default']
export const BioNav: typeof import("../components/BioNav.vue")['default']
export const BuildAnimation: typeof import("../components/BuildAnimation.vue")['default']
export const DarkModeToggle: typeof import("../components/DarkModeToggle.vue")['default']
export const FadeTransition: typeof import("../components/FadeTransition.vue")['default']
export const FunAnimation: typeof import("../components/FunAnimation.vue")['default']
export const HeadLine: typeof import("../components/HeadLine.vue")['default']
export const ImageSelector: typeof import("../components/ImageSelector.vue")['default']
export const Logo: typeof import("../components/Logo.vue")['default']
export const SocialCard: typeof import("../components/SocialCard.vue")['default']
export const SocialMediaBar: typeof import("../components/SocialMediaBar.vue")['default']
export const SupportAnimation: typeof import("../components/SupportAnimation.vue")['default']
export const VSvg: typeof import("../components/VSvg.vue")['default']
export const OutlineText: typeof import("../components/outline-text.vue")['default']
export const Project: typeof import("../components/project.vue")['default']
export const FormsTextInput: typeof import("../components/forms/TextInput.vue")['default']
export const IconsMenuIcon: typeof import("../components/icons/MenuIcon.vue")['default']
export const IconsSendIcon: typeof import("../components/icons/SendIcon.vue")['default']
export const UnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.44.7_vite@2.9.14/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const ContentDoc: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.mjs")['default']
export const ContentList: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentList.mjs")['default']
export const ContentNavigation: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.mjs")['default']
export const ContentQuery: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.mjs")['default']
export const ContentRenderer: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.mjs")['default']
export const Markdown: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Markdown.mjs")['default']
export const MarkdownRenderer: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/MarkdownRenderer.mjs")['default']
export const ProseA: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const ProseCodeInline: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const ProseEm: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue")['default']
export const ProseStrong: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.2/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const ColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.1.4_vite@2.9.14/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyTes: typeof import("../components/content/tes.vue")['default']
export const LazyAppFooter: typeof import("../components/AppFooter.vue")['default']
export const LazyAppHeader: typeof import("../components/AppHeader.vue")['default']
export const LazyBalanceAnimation: typeof import("../components/BalanceAnimation.vue")['default']
export const LazyBioNav: typeof import("../components/BioNav.vue")['default']
export const LazyBuildAnimation: typeof import("../components/BuildAnimation.vue")['default']
export const LazyDarkModeToggle: typeof import("../components/DarkModeToggle.vue")['default']
export const LazyFadeTransition: typeof import("../components/FadeTransition.vue")['default']
export const LazyFunAnimation: typeof import("../components/FunAnimation.vue")['default']
export const LazyHeadLine: typeof import("../components/HeadLine.vue")['default']
export const LazyImageSelector: typeof import("../components/ImageSelector.vue")['default']
export const LazyLogo: typeof import("../components/Logo.vue")['default']
export const LazySocialCard: typeof import("../components/SocialCard.vue")['default']
export const LazySocialMediaBar: typeof import("../components/SocialMediaBar.vue")['default']
export const LazySupportAnimation: typeof import("../components/SupportAnimation.vue")['default']
export const LazyVSvg: typeof import("../components/VSvg.vue")['default']
export const LazyOutlineText: typeof import("../components/outline-text.vue")['default']
export const LazyProject: typeof import("../components/project.vue")['default']
export const LazyFormsTextInput: typeof import("../components/forms/TextInput.vue")['default']
export const LazyIconsMenuIcon: typeof import("../components/icons/MenuIcon.vue")['default']
export const LazyIconsSendIcon: typeof import("../components/icons/SendIcon.vue")['default']
export const LazyUnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.44.7_vite@2.9.14/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const LazyContentDoc: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentDoc.mjs")['default']
export const LazyContentList: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentList.mjs")['default']
export const LazyContentNavigation: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.mjs")['default']
export const LazyContentQuery: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentQuery.mjs")['default']
export const LazyContentRenderer: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.mjs")['default']
export const LazyMarkdown: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Markdown.mjs")['default']
export const LazyMarkdownRenderer: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/MarkdownRenderer.mjs")['default']
export const LazyProseA: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue")['default']
export const LazyProseBlockquote: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue")['default']
export const LazyProseCode: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const LazyProseCodeInline: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const LazyProseEm: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue")['default']
export const LazyProseH2: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue")['default']
export const LazyProseH5: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue")['default']
export const LazyProseP: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue")['default']
export const LazyProseStrong: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../node_modules/.pnpm/@nuxt+content@2.0.1_vite@2.9.14/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.2/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_vite@2.9.14/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.1.4_vite@2.9.14/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const componentNames: string[]
